name: Build and Upload to Amazon ECR

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    types: [closed]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: bizio/bizio-support

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get version
      run: echo RELEASE_VERSION=$(awk -v n=0 '/<version[^>]*>(.*?)-SNAPSHOT<\/version>/{if($1!=""){n=1}} {if(n==1){print $1; exit}}' pom.xml | sed 's/<version>//g' | sed 's/-SNAPSHOT<\/version>//g' | sed 's/[\t ]//g;/^$/d') >> $GITHUB_ENV
  
    - name: Build, tag image
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$RELEASE_VERSION --build-arg BUILD_VERSION=${{ env.RELEASE_VERSION }} .
        docker image tag $ECR_REGISTRY/$ECR_REPOSITORY:$RELEASE_VERSION $ECR_REGISTRY/$ECR_REPOSITORY:latest
        
    - name: Push image to Amazon ECR
      id: push-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$RELEASE_VERSION
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
